import 'dart:async';
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:llama_cpp_dart/llama_cpp_dart.dart';
import 'package:path_provider/path_provider.dart';

class LlamaEngine {
  static final LlamaEngine _instance = LlamaEngine._internal();
  factory LlamaEngine() => _instance;
  LlamaEngine._internal();

  Llama? _llama;
  bool _isModelLoaded = false;
  bool _isLoadingModel = false;
  String? _modelPath;
  String? _lastError;

  bool get isModelLoaded => _isModelLoaded && _llama != null;
  bool get isLoadingModel => _isLoadingModel;
  String? get lastError => _lastError;

  /// Initializes and caches the Qwen 2.5 0.5B Instruct GGUF model in application storage
  Future<void> initializeModel({String modelAssetName = 'qwen2.5-0.5b-instruct-q4_k_m.gguf'}) async {
    if (_isModelLoaded && _llama != null) return;
    if (_isLoadingModel) return;
    _isLoadingModel = true;
    _lastError = null;

    try {
      final appDocDir = await getApplicationDocumentsDirectory();
      final targetFile = File('${appDocDir.path}/$modelAssetName');
      final localAssetFile = File('assets/models/$modelAssetName');

      if (await localAssetFile.exists() && localAssetFile.lengthSync() > 1000000) {
        _modelPath = localAssetFile.path;
        debugPrint('[LlamaEngine] Model file found: $_modelPath');
      } else if (await targetFile.exists() && targetFile.lengthSync() > 1000000) {
        _modelPath = targetFile.path;
        debugPrint('[LlamaEngine] Model file cached: $_modelPath');
      } else {
        try {
          debugPrint('[LlamaEngine] Unpacking model asset to storage (${targetFile.path})...');
          final byteData = await rootBundle.load('assets/models/$modelAssetName');
          final buffer = byteData.buffer;
          await targetFile.writeAsBytes(
            buffer.asUint8List(byteData.offsetInBytes, byteData.lengthInBytes),
            flush: true,
          );
          _modelPath = targetFile.path;
          debugPrint('[LlamaEngine] Model copy success: $_modelPath');
        } catch (e) {
          debugPrint('[LlamaEngine] Asset bundle load notice: $e');
        }
      }

      if (_modelPath != null && File(_modelPath!).existsSync()) {
        debugPrint('[LlamaEngine] Native libraries loading (libllama.so, libmtmd.so)...');
        debugPrint('[LlamaEngine] Initializing native llama.cpp instance with $_modelPath...');
        final contextParams = ContextParams()
          ..nCtx = 2048
          ..nBatch = 512;
        final samplerParams = SamplerParams()
          ..temp = 0.3
          ..topP = 0.9;

        _llama = Llama(
          _modelPath!,
          contextParams: contextParams,
          samplerParams: samplerParams,
        );
        debugPrint('[LlamaEngine] Model load success: Qwen 2.5 0.5B Instruct GGUF');
        debugPrint('[LlamaEngine] Inference ready.');
        _isModelLoaded = true;
      } else {
        _lastError = 'Model file not found at $_modelPath';
        debugPrint('[LlamaEngine] Error: $_lastError');
      }
    } catch (e) {
      _lastError = e.toString();
      debugPrint('[LlamaEngine] Native Llama init error: $e');
    } finally {
      _isLoadingModel = false;
    }
  }

  /// Streams token-by-token output directly from the Qwen 2.5 0.5B Instruct GGUF neural network
  Stream<String> generateStreaming({
    required String prompt,
    String? userQuery,
    required String curriculumContext,
    int maxTokens = 150,
    double temperature = 0.3,
  }) async* {
    if (_llama == null || !_isModelLoaded) {
      debugPrint('[LlamaEngine] Model not ready yet. Initializing now...');
      await initializeModel();
    }

    if (_llama != null) {
      try {
        final formattedPrompt = prompt.contains('<|im_start|>')
            ? prompt
            : '<|im_start|>system\n'
                'You are Dendy, Questly\'s friendly fox learning companion.\n'
                'Rules:\n'
                '- Only answer using the curriculum below.\n'
                '- Keep answers simple, short, and encourage the student.\n\n'
                'Curriculum:\n$curriculumContext<|im_end|>\n'
                '<|im_start|>user\n${userQuery ?? prompt}<|im_end|>\n'
                '<|im_start|>assistant\n';

        debugPrint('[LlamaEngine] Setting prompt to native Qwen LLM (${formattedPrompt.length} chars)');
        _llama!.setPrompt(formattedPrompt);
        
        final tokenStream = _llama!.generateText();
        int tokenCount = 0;

        await for (final token in tokenStream) {
          if (token.contains('<|im_end|>') || token.contains('<|endoftext|>')) {
            break;
          }
          tokenCount++;
          yield token;
        }
        debugPrint('[LlamaEngine] Generation complete ($tokenCount tokens generated by Qwen 2.5)');
        return;
      } catch (e) {
        debugPrint('[LlamaEngine] Native token generation error: $e');
        yield '[Dendy AI]: Error generating from neural network ($e). Please try asking again.';
        return;
      }
    }

    // If model failed to load on device, explicitly notify the user
    yield '[Dendy Offline AI]: Loading Qwen 2.5 model into device memory... Please wait a few seconds and ask again!';
  }
}
