import 'package:flutter/foundation.dart';
import '../core/locator.dart';
import 'storage_service.dart';

class LocalizationService {
  static String _currentLanguage = 'en';
  static final ValueNotifier<String> languageNotifier = ValueNotifier<String>('en');

  static String get currentLanguage => _currentLanguage;

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Navigation & Dashboard
      'continue_learning': 'Continue Learning',
      'your_quest': 'YOUR QUEST',
      'lesson_progress': 'Lesson {current} of {total}',
      'continue_quest': 'CONTINUE QUEST',
      'start_quest': 'START QUEST',
      'revision': 'Revision',
      'quick_revision': 'QUICK REVISION',
      'concepts_ready': '{count} concepts ready for review',
      'start_revision': 'START REVISION',
      'my_modules': 'My Modules',
      'view_all': 'VIEW ALL',
      'view_all_modules': 'VIEW ALL MODULES',
      'leaderboard': 'Leaderboard',
      'your_class': 'YOUR CLASS',
      'view_leaderboard': 'VIEW LEADERBOARD',
      'collection': 'Collection',
      'shop': 'Shop',
      'settings': 'Settings',
      'profile': 'Profile',
      'badges': 'Badges',
      'collectibles': 'Collectibles',
      'account': 'Account',
      'logout': 'Log Out',
      'language': 'Language',
      'sound': 'Sound Effects',
      'student_id': 'Student ID',
      'notifications': 'Notifications',
      'quest_coins': 'Quest Coins',
      'level': 'Level',
      'completed': 'Completed',
      'current': 'Current',
      'locked': 'Locked',
      'insufficient_coins': 'Not enough Quest Coins! Keep learning to earn more.',
      'purchase_success': 'Successfully purchased!',
      'already_owned': 'You already own this item!',
      'start_module': 'START MODULE',
      'continue_module': 'CONTINUE MODULE',
      'roadmap': 'Roadmap',
      'explore_modules': 'EXPLORE MODULES',
      'start_first_quest': 'START YOUR FIRST QUEST',
      'quest_complete': 'QUEST COMPLETE!',
      'all_caught_up': "You're all caught up!",
      'change_language': 'Change Language',
      'home': 'Home',
      'back': 'BACK',
      'close': 'Close',

      // Missions
      'missions': 'Missions',
      'daily_missions': 'DAILY MISSIONS',
      'weekly_missions': 'WEEKLY MISSIONS',
      'daily': 'DAILY',
      'weekly': 'WEEKLY',
      'resets_daily': 'Resets daily at midnight',
      'resets_weekly': 'Resets every Monday',
      'claim_reward_btn': 'CLAIM REWARD!',
      'claimed_btn': 'CLAIMED',
      'complete_2_lessons': 'Complete 2 Lessons',
      'earn_100_xp': 'Earn 100 XP',
      'finish_1_simulation_lab': 'Finish 1 Simulation Lab',
      'master_1_full_module': 'Master 1 Full Module',
      'earn_500_weekly_xp': 'Earn 500 Weekly XP',
      'complete_any_2_curiosity_or_lab_lessons': 'Complete any 2 curiosity or lab lessons',
      'gain_100_xp_from_quests_and_activities': 'Gain 100 XP from quests and activities',
      'conduct_any_phet_or_titration_lab_experiment': 'Conduct any PhET or titration lab experiment',
      'finish_all_5_interactive_lessons_in_a_topic': 'Finish all 5 interactive lessons in a topic',
      'gather_500_total_xp_across_the_entire_week': 'Gather 500 total XP across the entire week',

      // Daily Rewards
      'daily_login_reward': 'DAILY LOGIN REWARD',
      'day_streak': '{day}-Day Streak',
      'streak_day': 'Day {day}',
      'claim_reward': 'CLAIM REWARD',
      'mystery_chest': 'MYSTERY CHEST',
      'reward_claimed': 'REWARD CLAIMED!',
      'come_back_tomorrow': 'Come back tomorrow for Day {day} reward!',
      'streak_complete': '7-day streak complete! Next cycle begins tomorrow.',
      'claimed': 'CLAIMED',

      // Ask Dendy
      'ask_dendy': 'ASK DENDY',
      'dendy_companion': 'Dendy AI Companion',
      'ask_me_anything': 'Ask me anything about science or math!',
      'listening': 'Listening...',
      'tap_to_speak': 'Tap mic to speak or type below',
      'type_question': 'Type your question...',
      'suggested_questions': 'Suggested Questions:',
      'why_wood_float': 'Why does wood float in water?',
      'how_steel_ships_float': 'How do steel ships float?',
      'why_ice_float': 'Why does ice float?',
      'what_is_density': 'What is density?',
      'what_is_titration': 'What is titration in chemistry?',
      'dendy_learning_fallback': "I'm still learning! My offline AI will answer this in a future version. Try asking me about density, floating, buoyancy, titration, or fractions!",

      // Dendy Dialogues & Mascots
      'ready_next_quest': 'Ready for your next quest?',
      'almost_done_lesson': 'You are almost done with this lesson!',
      'all_science_quests_complete': 'Excellent! You completed all the physical science lab quests!',
      'start_first_quest_desc': "Start your first quest! Let's find something new to explore!",
      'investigate_reasons_lab': 'We will investigate the exact reasons and measurements in the next experiment lab!',
      'discovery_complete': 'DISCOVERY COMPLETE!',
      'predictions_tested': 'You made your predictions and tested them.',
      'carefully_check_parameters': 'Carefully check the parameters before selecting your answer!',
      'keep_trying_density_formula': 'Keep trying! Think about the density formula.',
      'lab_description': 'LAB DESCRIPTION',
      'titration_objectives': 'TITRATION OBJECTIVES',
      'apparatus_selection': '1. Apparatus Selection',
      'level_up': 'LEVEL UP!',
      'reached_level': 'YOU REACHED LEVEL {level}!',
      'continue_adventure': 'CONTINUE ADVENTURE',
      'bonus_xp': 'Bonus XP',
      'rank_promoted': 'Promoted',
      'fantastic_job_mastered': 'Fantastic job! You mastered this challenge and earned rewards.',
      'continue_next_lesson': 'CONTINUE TO NEXT LESSON',

      // Scientific Concepts
      'steel_ship_explanation': 'A hollow steel ship floats because the air trapped inside its massive hull lowers its total average density below 1.00 kg/L.',
      'ice_expands_title': 'Ice Expands & Defies Normal Solids',
      'ice_expands_body': 'Water expands when freezing, giving ice a density of 0.92 kg/L. That is why ice floats and supports Arctic life.',
      'liquids_layer_title': 'Liquids Naturally Layer by Density',
      'liquids_layer_body': 'When immiscible fluids meet, lighter fluids (like oil at ~0.92 kg/L) float on top of denser fluids (like water at 1.00 kg/L).',
      'complete_and_unlock': 'COMPLETE & UNLOCK CHALLENGE',

      // Interactive Lessons (Discover Density & Buoyancy)
      'level_1_title': 'LEVEL 1 • DISCOVER DENSITY',
      'lesson_counter': 'LESSON {current} OF {total}',
      'curiosity': 'CURIOSITY',
      'experiment': 'EXPERIMENT',
      'apply': 'APPLY',
      'challenge': 'CHALLENGE',
      'teach_dendy': 'TEACH DENDY',
      'discovery_lab_step_1': 'DISCOVERY LAB • STEP 1',
      'discover_density': 'DISCOVER DENSITY',
      'why_objects_float_sink': '"Why do some objects float while others sink?"',
      'predict_before_test': 'Before testing, predict what will happen when different materials are placed in water. Observe the physical results and notice what happens.',
      'start_discovery': 'START DISCOVERY',
      'predict_before_test_dendy': "Let's make a prediction before we test anything!",
      'wooden_block': 'WOODEN BLOCK',
      'solid_oak_wood': 'Solid oak wood',
      'metal_cube': 'METAL CUBE',
      'solid_iron_steel': 'Solid iron/steel',
      'plastic_ball': 'PLASTIC BALL',
      'hollow_plastic': 'Hollow lightweight plastic',
      'river_stone': 'RIVER STONE',
      'dense_pebble': 'Dense smooth pebble',
      'apple': 'APPLE',
      'fresh_fruit': 'Fresh crisp fruit',
      'float': 'FLOAT',
      'sink': 'SINK',
      'test_hypothesis': 'TEST HYPOTHESIS',
      'water_tank_lab': 'WATER TANK LAB',
      'tap_to_test': 'TAP AN OBJECT TO TEST',
      'what_did_you_observe': 'WHAT DID YOU OBSERVE?',
      'reflection_wood_plastic_float': 'Wood & plastic float because they are less dense than water. Metal & stone sink because they are denser.',
      'reflection_heavy_sink': 'Heavy things always sink and light things always float.',
      'reflection_shape_only': 'Shape is the only reason objects float.',
      'continue_to_lesson_2': 'CONTINUE TO LESSON 2',
      'lesson_2_measure_density': 'LESSON 2: MEASURE DENSITY',
      'lesson_2_title_progress': 'Lesson 2 of 5',
      'mass_volume_lab': 'MASS & VOLUME LAB',
      'change_mass_volume_desc': 'Change mass and volume to see density change in real time!',
      'mass_kg': 'Mass (kg)',
      'volume_l': 'Volume (L)',
      'density_formula_desc': 'Density = Mass ÷ Volume',
      'water_density_standard': 'Water Density: 1.00 kg/L',
      'reset_lab': 'RESET LAB',
      'nice_prediction_become_scientists': "Nice prediction. Now let's become scientists.",
      'lets_experiment': "Let's experiment.",
      'try_making_object_heavier': "Try making this object heavier.",
      'what_changed': "What changed?",
      'sank_deeper': "Sank deeper",
      'floated_higher': "Floated higher",
      'nothing_changed': "Nothing changed",
      'what_happens_change_size': "What happens if we change the size instead?",
      'what_do_you_notice': "What do you notice?",
      'compare_two_objects': "Now let's compare two objects side by side in the tank.",
      'which_one_sinks_more': "Which one sinks more?",
      'denser_heavier_object': "The denser object",
      'larger_lighter_object': "The lighter object",
      'both_sink_equally': "Both sink equally",
      'compare_mode': "Compare Mode",
      'single_mode': "Single Object",
      'object_a': "Object A",
      'object_b': "Object B",
      'mat_wood': "Wood",
      'mat_ice': "Ice",
      'mat_plastic': "Plastic",
      'mat_steel': "Steel",
      'mat_gold': "Gold",
      'youve_changed_mass': "You've changed the mass.",
      'youve_changed_volume': "You've changed the volume.",
      'can_you_spot_pattern': "Can you spot the pattern?",
      'the_density_formula': "THE DENSITY FORMULA",
      'density_equals_mass_divided_volume': "Density = Mass ÷ Volume",
      'density_discovery_desc': "When mass increases in the same volume, density goes up. When volume increases for the same mass, density goes down!",
      'less_dense_than_water_floats': "Less dense than water (< 1.00 kg/L) = FLOATS!",
      'more_dense_than_water_sinks': "Denser than water (> 1.00 kg/L) = SINKS!",
      'continue_to_lesson_3': 'CONTINUE TO LESSON 3',
      'lesson_3_real_world': 'LESSON 3: REAL-WORLD DENSITY',
      'apply_your_knowledge': 'APPLY YOUR KNOWLEDGE',
      'why_steel_ships_float_q': 'Why do huge steel ships float on water?',
      'why_ice_floats_q': 'Why does ice float on water?',
      'why_oil_floats_q': 'Why does oil float on water?',
      'lesson_4_detective': 'LESSON 4: DENSITY DETECTIVE',
      'mystery_objects': 'MYSTERY OBJECTS',
      'identify_gold_desc': 'Identify which object is made of gold based on density!',
      'submit_answer': 'SUBMIT ANSWER',
      'lesson_5_teach_dendy': 'LESSON 5: TEACH DENDY',
      'explain_density_dendy': 'Explain to Dendy why objects float or sink using mass and volume!',
      'density_mastered': 'DENSITY MASTERED',
      'level_1_complete': 'LEVEL 1 COMPLETE',
      'claim_rewards_unlock_2': 'CLAIM REWARDS & UNLOCK LEVEL 2',

      // Greeting & Profile Stats
      'greeting_hi': 'Hi',
      'total_xp': 'TOTAL XP',
      'coins': 'COINS',
      'stat_completed': 'COMPLETED',
      'stat_badges': 'BADGES',
      'stat_collectibles': 'COLLECTIBLES',
      'stat_offline_sync': 'OFFLINE SYNC',
      'ready': 'Ready',
      'earned': 'Earned',
      'unlocked': 'Unlocked',
      'modules': 'Modules',
      'lessons': 'Lessons',
      'levels': 'Levels',
      'objectives_header': 'OBJECTIVES:',

      // Subjects & Modules
      'SCIENCE': 'SCIENCE',
      'MATHEMATICS': 'MATHEMATICS',
      'CHEMISTRY': 'CHEMISTRY',
      'PHYSICS': 'PHYSICS',
      'VIRTUAL LAB': 'VIRTUAL LAB',
      'mod_density_title': 'Density & Buoyancy',
      'mod_fractions_title': 'Fractions',
      'mod_titration_title': 'Acid-Base Titration',
      'mod_ratios_title': 'Ratio & Proportions',
      'mod_density_desc': 'Explore the physics of mass, volume, and how materials behave in fluids.',
      'mod_fractions_desc': 'Master parts of a whole, visual fractions, and equivalent ratios.',
      'mod_titration_desc': 'Master neutralization reactions, indicators, and precise lab measurements.',

      // Badges, Shop & Collections
      'badge_explorer': 'Explorer',
      'badge_scientist': 'Scientist',
      'badge_master': 'Master',
      'badge_champion': 'Champion',
      'shop_buy': 'BUY',
      'shop_owned': 'OWNED',
      'insufficient_coins_title': 'INSUFFICIENT COINS',
      'purchase_successful_title': 'PURCHASE SUCCESSFUL!',
      'already_owned_title': 'ALREADY OWNED',
      'rank_student_header': 'RANK / STUDENT',
      'total_score_header': 'TOTAL SCORE',
    },
    'ta': {
      // Navigation & Dashboard
      'continue_learning': 'தொடர்ந்து கற்கவும்',
      'your_quest': 'உங்களது தேடல்',
      'lesson_progress': 'பாடம் {current} இல் {total}',
      'continue_quest': 'தேடலைத் தொடரவும்',
      'start_quest': 'தேடலைத் தொடங்கு',
      'revision': 'திருப்புதல்',
      'quick_revision': 'விரைவு திருப்புதல்',
      'concepts_ready': '{count} கருத்துக்கள் திருப்புதலுக்குத் தயார்',
      'start_revision': 'திருப்புதலைத் தொடங்கு',
      'my_modules': 'எனது பாடங்கள்',
      'view_all': 'அனைத்தையும் பார்',
      'view_all_modules': 'அனைத்து பாடங்களையும் பார்',
      'leaderboard': 'மதிப்பெண் பட்டியல்',
      'your_class': 'உங்களது வகுப்பு',
      'view_leaderboard': 'மதிப்பெண் பட்டியலை பார்',
      'collection': 'சேகரிப்புகள்',
      'shop': 'கடை',
      'settings': 'அமைப்புகள்',
      'profile': 'சுயவிவரம்',
      'badges': 'சின்னங்கள்',
      'collectibles': 'சேகரிக்கப்பட்டவை',
      'account': 'கணக்கு',
      'logout': 'வெளியேறு',
      'language': 'மொழி',
      'sound': 'ஒலி விளைவுகள்',
      'student_id': 'மாணவர் ஐடி',
      'notifications': 'அறிவிப்புகள்',
      'quest_coins': 'தேடல் நாணயங்கள்',
      'level': 'நிலை',
      'completed': 'முடிக்கப்பட்டது',
      'current': 'தற்போதைய',
      'locked': 'பூட்டப்பட்டது',
      'insufficient_coins': 'தேவையான நாணயங்கள் இல்லை! மேலும் நாணயங்கள் பெற தொடர்ந்து கற்கவும்.',
      'purchase_success': 'வெற்றிகரமாக வாங்கப்பட்டது!',
      'already_owned': 'நீங்கள் ஏற்கனவே இதை வாங்கியுள்ளீர்கள்!',
      'start_module': 'பாடத்தைத் தொடங்கு',
      'continue_module': 'பாடத்தைத் தொடரவும்',
      'roadmap': 'பயண வழி',
      'explore_modules': 'பாடங்களை ஆராய்',
      'start_first_quest': 'முதல் தேடலைத் தொடங்கு',
      'quest_complete': 'தேடல் முடிந்தது!',
      'all_caught_up': 'அனைத்தும் படித்து முடிக்கப்பட்டது!',
      'change_language': 'மொழியை மாற்று',
      'home': 'முகப்பு',
      'back': 'பின்செல்',
      'close': 'மூடு',

      // Missions
      'missions': 'பணிகள்',
      'daily_missions': 'தினசரி பணிகள்',
      'weekly_missions': 'வாராந்திர பணிகள்',
      'daily': 'தினசரி',
      'weekly': 'வாராந்திரம்',
      'resets_daily': 'தினமும் நள்ளிரவில் புதுப்பிக்கப்படும்',
      'resets_weekly': 'ஒவ்வொரு திங்கட்கிழமையும் புதுப்பிக்கப்படும்',
      'claim_reward_btn': 'பரிசைப் பெறு!',
      'claimed_btn': 'பெறப்பட்டது',
      'complete_2_lessons': '2 பாடங்களை முடிக்கவும்',
      'earn_100_xp': '100 XP சம்பாதிக்கவும்',
      'finish_1_simulation_lab': '1 ஆய்வக பரிசோதனையை முடிக்கவும்',
      'master_1_full_module': '1 முழு பாடப்பிரிவில் தேர்ச்சி பெறவும்',
      'earn_500_weekly_xp': '500 வாராந்திர XP சம்பாதிக்கவும்',
      'complete_any_2_curiosity_or_lab_lessons': 'ஏதேனும் 2 ஆய்வக அல்லது தேடல் பாடங்களை முடிக்கவும்',
      'gain_100_xp_from_quests_and_activities': 'பாடங்கள் மற்றும் செயல்களில் இருந்து 100 XP பெறவும்',
      'conduct_any_phet_or_titration_lab_experiment': 'ஏதேனும் ஒரு PhET அல்லது டைட்ரேஷன் பரிசோதனையைச் செய்யவும்',
      'finish_all_5_interactive_lessons_in_a_topic': 'ஒரு தலைப்பில் உள்ள அனைத்து 5 பாடங்களையும் முடிக்கவும்',
      'gather_500_total_xp_across_the_entire_week': 'வாரம் முழுவதும் மொத்தம் 500 XP பெறவும்',

      // Daily Rewards
      'daily_login_reward': 'தினசரி உள்நுழைவு பரிசு',
      'day_streak': '{day}-நாள் தொடர்',
      'streak_day': 'நாள் {day}',
      'claim_reward': 'பரிசைப் பெறு',
      'mystery_chest': 'மர்மப் பெட்டி',
      'reward_claimed': 'பரிசு பெறப்பட்டது!',
      'come_back_tomorrow': 'நாள் {day} பரிசுக்காக நாளை மீண்டும் வாருங்கள்!',
      'streak_complete': '7-நாள் தொடர் முடிந்தது! அடுத்த சுழற்சி நாளை தொடங்கும்.',
      'claimed': 'பெறப்பட்டது',

      // Ask Dendy
      'ask_dendy': 'டெண்டியிடம் கேள்',
      'dendy_companion': 'டெண்டி AI தோழன்',
      'ask_me_anything': 'அறிவியல் அல்லது கணிதம் பற்றி என்னிடம் எதையும் கேளுங்கள்!',
      'listening': 'கேட்கிறது...',
      'tap_to_speak': 'பேச மைக்-ஐ அழுத்தவும் அல்லது கீழே தட்டச்சு செய்யவும்',
      'type_question': 'உங்கள் கேள்வியைத் தட்டச்சு செய்க...',
      'suggested_questions': 'பரிந்துரைக்கப்பட்ட கேள்விகள்:',
      'why_wood_float': 'மரம் ஏன் தண்ணீரில் மிதக்கிறது?',
      'how_steel_ships_float': 'எஃகு கப்பல்கள் எவ்வாறு மிதக்கின்றன?',
      'why_ice_float': 'பனிக்கட்டி ஏன் மிதக்கிறது?',
      'what_is_density': 'அடர்த்தி என்றால் என்ன?',
      'what_is_titration': 'வேதியியலில் டைட்ரேஷன் என்றால் என்ன?',
      'dendy_learning_fallback': 'நான் இன்னும் கற்றுக்கொண்டு வருகிறேன்! எனது ஆஃப்லைன் AI எதிர்கால பதிப்பில் இதற்குப் பதிலளிக்கும். அடர்த்தி, மிதத்தல், மிதப்பு விசை, அல்லது பின்னங்கள் பற்றி என்னிடம் கேளுங்கள்!',

      // Dendy Dialogues & Mascots
      'ready_next_quest': 'உங்களது அடுத்த தேடலுக்குத் தயாரா?',
      'almost_done_lesson': 'நீங்கள் இந்த பாடத்தை கிட்டத்தட்ட முடித்துவிட்டீர்கள்!',
      'all_science_quests_complete': 'அற்புதம்! அனைத்து இயற்பியல் அறிவியல் ஆய்வக தேடல்களையும் முடித்துவிட்டீர்கள்!',
      'start_first_quest_desc': 'உங்கள் முதல் தேடலைத் தொடங்குங்கள்! புதியதைக் கற்றுக்கொள்வோம்!',
      'investigate_reasons_lab': 'அடுத்த ஆய்வகத்தில் இதற்கான சரியான காரணங்களையும் அளவீடுகளையும் நாம் ஆராய்வோம்!',
      'discovery_complete': 'கண்டுபிடிப்பு முடிந்தது!',
      'predictions_tested': 'நீங்கள் உங்களது கணிப்புகளைச் செய்து அவற்றை சோதித்தீர்கள்.',
      'carefully_check_parameters': 'பதிலைத் தேர்ந்தெடுப்பதற்கு முன் அளவுருக்களை கவனமாகச் சரிபார்க்கவும்!',
      'keep_trying_density_formula': 'தொடர்ந்து முயற்சிக்கவும்! அடர்த்தி சூத்திரத்தை நினைவில் கொள்ளுங்கள்.',
      'lab_description': 'ஆய்வக விளக்கம்',
      'titration_objectives': 'டைட்ரேஷன் நோக்கங்கள்',
      'apparatus_selection': '1. கருவிகள் தேர்வு',
      'level_up': 'புதிய நிலை!',
      'reached_level': 'நீங்கள் நிலை {level}-ஐ அடைந்துவிட்டீர்கள்!',
      'continue_adventure': 'பயணத்தைத் தொடரவும்',
      'bonus_xp': 'கூடுதல் XP',
      'rank_promoted': 'பதவி உயர்வு',
      'fantastic_job_mastered': 'அருமையான வேலை! நீங்கள் இந்த சவாலில் தேர்ச்சி பெற்று பரிசுகளைப் பெற்றுள்ளீர்கள்.',
      'continue_next_lesson': 'அடுத்த பாடத்திற்குச் செல்லவும்',

      // Scientific Concepts
      'steel_ship_explanation': 'ஒரு வெற்று எஃகு கப்பல் மிதக்கிறது, ஏனெனில் அதன் உள்ளே உள்ள காற்று அதன் மொத்த சராசரி அடர்த்தியைக் குறைக்கிறது.',
      'ice_expands_title': 'பனிக்கட்டி விரிவடைகிறது மற்றும் சாதாரண திடப்பொருட்களை விட மாறுபடுகிறது',
      'ice_expands_body': 'நீர் உறையும் போது விரிவடைந்து 0.92 kg/L அடர்த்தியைப் பெறுகிறது. அதனால்தான் பனிக்கட்டி மிதக்கிறது.',
      'liquids_layer_title': 'திரவங்கள் அடர்த்தியின் அடிப்படையில் இயல்பாக அடுக்குகளாக அமைகின்றன',
      'liquids_layer_body': 'கலக்காத திரவங்கள் சேரும்போது, குறைந்த அடர்த்தி கொண்ட திரவங்கள் (எண்ணெய் போன்றவை) அதிக அடர்த்தி கொண்ட திரவங்களின் மேல் மிதக்கின்றன.',
      'complete_and_unlock': 'முடிக்கப்பட்டு சவாலைத் திறக்கவும்',

      // Interactive Lessons (Discover Density & Buoyancy)
      'level_1_title': 'நிலை 1 • அடர்த்தியைக் கண்டுபிடி',
      'lesson_counter': 'பாடம் {current} இன் {total}',
      'curiosity': 'தேடல்',
      'experiment': 'பரிசோதனை',
      'apply': 'பயன்படுத்து',
      'challenge': 'சவால்',
      'teach_dendy': 'டெண்டிக்குக் கற்றுக்கொடு',
      'discovery_lab_step_1': 'கண்டுபிடிப்பு ஆய்வகம் • படி 1',
      'discover_density': 'அடர்த்தியைக் கண்டுபிடி',
      'why_objects_float_sink': '"சில பொருட்கள் ஏன் மிதக்கின்றன, மற்றவை ஏன் மூழ்குகின்றன?"',
      'predict_before_test': 'சோதிப்பதற்கு முன், வெவ்வேறு பொருட்கள் தண்ணீரில் போடப்படும்போது என்ன நடக்கும் என்று கணிக்கவும். முடிவுகளைக் கவனியுங்கள்.',
      'start_discovery': 'கண்டுபிடிப்பைத் தொடங்கு',
      'predict_before_test_dendy': 'எதையும் சோதிக்கும் முன் ஒரு கணிப்பை உருவாக்குவோம்!',
      'wooden_block': 'மரக் கட்டை',
      'solid_oak_wood': 'திடமான தேக்கு மரம்',
      'metal_cube': 'உலோகக் கனசதுரம்',
      'solid_iron_steel': 'திடமான இரும்பு / எஃகு',
      'plastic_ball': 'பிளாஸ்டிக் பந்து',
      'hollow_plastic': 'வெற்று இலகுவான பிளாஸ்டிக்',
      'river_stone': 'ஆற்றுக் கல்',
      'dense_pebble': 'அடர்த்தியான வழவழப்பான கல்',
      'apple': 'ஆப்பிள்',
      'fresh_fruit': 'புதிய பழம்',
      'float': 'மிதக்கும்',
      'sink': 'மூழ்கும்',
      'test_hypothesis': 'கணிப்பை சோதி',
      'water_tank_lab': 'தண்ணீர்த் தொட்டி ஆய்வகம்',
      'tap_to_test': 'சோதிக்க ஒரு பொருளைத் தட்டவும்',
      'what_did_you_observe': 'நீங்கள் என்ன கவனித்தீர்கள்?',
      'reflection_wood_plastic_float': 'மரம் மற்றும் பிளாஸ்டிக் தண்ணீரை விட அடர்த்தி குறைவாக இருப்பதால் மிதக்கின்றன. உலோகம் மற்றும் கல் அதிக அடர்த்தி கொண்டவை என்பதால் மூழ்குகின்றன.',
      'reflection_heavy_sink': 'கனமானவை எப்போதும் மூழ்கும், இலகுவானவை எப்போதும் மிதக்கும்.',
      'reflection_shape_only': 'வடிவம் மட்டுமே பொருட்கள் மிதப்பதற்குக் காரணம்.',
      'continue_to_lesson_2': 'பாடம் 2-க்குச் செல்லவும்',
      'lesson_2_measure_density': 'பாடம் 2: அடர்த்தியை அளவிடுதல்',
      'lesson_2_title_progress': 'பாடம் 2 இல் 5',
      'mass_volume_lab': 'திணிவு மற்றும் கனஅளவு ஆய்வகம்',
      'change_mass_volume_desc': 'திணிவு மற்றும் கனஅளவை மாற்றி அடர்த்தி நிகழ்நேரத்தில் மாறுவதைக் காண்க!',
      'mass_kg': 'திணிவு (kg)',
      'volume_l': 'கனஅளவு (L)',
      'density_formula_desc': 'அடர்த்தி = திணிவு ÷ கனஅளவு',
      'water_density_standard': 'நீரின் அடர்த்தி: 1.00 kg/L',
      'reset_lab': 'மீட்டமை',
      'nice_prediction_become_scientists': 'அருமையான கணிப்பு. இப்போது நாம் விஞ்ஞானிகளாவோம்.',
      'lets_experiment': 'வாருங்கள் பரிசோதிப்போம்.',
      'try_making_object_heavier': 'இந்தப் பொருளைக் கூடுதல் எடையுள்ளதாக மாற்ற முயற்சிக்கவும்.',
      'what_changed': 'என்ன மாறியது?',
      'sank_deeper': 'ஆழமாக மூழ்கியது',
      'floated_higher': 'உயரமாக மிதந்தது',
      'nothing_changed': 'எதுவும் மாறவில்லை',
      'what_happens_change_size': 'அளவை மாற்றினால் என்ன நடக்கும்?',
      'what_do_you_notice': 'நீங்கள் என்ன கவனிக்கிறீர்கள்?',
      'compare_two_objects': 'இப்போது தொட்டியில் இரண்டு பொருட்களை அருகருகே ஒப்பிடுவோம்.',
      'which_one_sinks_more': 'எது அதிகமாக மூழ்குகிறது?',
      'denser_heavier_object': 'அதிக அடர்த்தியுள்ள பொருள்',
      'larger_lighter_object': 'குறைந்த எடையுள்ள பொருள்',
      'both_sink_equally': 'இரண்டும் சமமாக மூழ்குகின்றன',
      'compare_mode': 'ஒப்பீட்டு முறை',
      'single_mode': 'ஒற்றைப் பொருள்',
      'object_a': 'பொருள் A',
      'object_b': 'பொருள் B',
      'mat_wood': 'மரம்',
      'mat_ice': 'பனிக்கட்டி',
      'mat_plastic': 'பிளாஸ்டிக்',
      'mat_steel': 'எஃகு',
      'mat_gold': 'தங்கம்',
      'youve_changed_mass': 'நீங்கள் திணிவை மாற்றியுள்ளீர்கள்.',
      'youve_changed_volume': 'நீங்கள் கனஅளவை மாற்றியுள்ளீர்கள்.',
      'can_you_spot_pattern': 'உங்களால் வடிவ அமைப்பைக் கண்டுபிடிக்க முடிகிறதா?',
      'the_density_formula': 'அடர்த்தி சூத்திரம்',
      'density_equals_mass_divided_volume': 'அடர்த்தி = திணிவு ÷ கனஅளவு',
      'density_discovery_desc': 'ஒரே கனஅளவில் திணிவு கூடும் போது அடர்த்தி கூடுகிறது. ஒரே திணிவுக்கு கனஅளவு கூடும் போது அடர்த்தி குறைகிறது!',
      'less_dense_than_water_floats': 'தண்ணீரை விட அடர்த்தி குறைவு (< 1.00 kg/L) = மிதக்கும்!',
      'more_dense_than_water_sinks': 'தண்ணீரை விட அடர்த்தி அதிகம் (> 1.00 kg/L) = மூழ்கும்!',
      'continue_to_lesson_3': 'பாடம் 3-க்குச் செல்லவும்',
      'lesson_3_real_world': 'பாடம் 3: நிஜ உலக அடர்த்தி',
      'apply_your_knowledge': 'உங்கள் அறிவைப் பயன்படுத்துங்கள்',
      'why_steel_ships_float_q': 'மிகப் பெரிய எஃகு கப்பல்கள் தண்ணீரில் ஏன் மிதக்கின்றன?',
      'why_ice_floats_q': 'பனிக்கட்டி தண்ணீரில் ஏன் மிதக்கிறது?',
      'why_oil_floats_q': 'எண்ணெய் தண்ணீரில் ஏன் மிதக்கிறது?',
      'lesson_4_detective': 'பாடம் 4: அடர்த்தி துப்பறிவாளர்',
      'mystery_objects': 'மர்மப் பொருட்கள்',
      'identify_gold_desc': 'அடர்த்தியின் அடிப்படையில் எந்தப் பொருள் தங்கத்தால் ஆனது என்பதைக் கண்டறியவும்!',
      'submit_answer': 'பதிலைச் சமர்ப்பி',
      'lesson_5_teach_dendy': 'பாடம் 5: டெண்டிக்குக் கற்றுக்கொடு',
      'explain_density_dendy': 'திணிவு மற்றும் கனஅளவைப் பயன்படுத்தி பொருட்கள் ஏன் மிதக்கின்றன அல்லது மூழ்குகின்றன என்பதை டெண்டிக்கு விளக்குங்கள்!',
      'density_mastered': 'அடர்த்தி தேர்ச்சி பெற்றது',
      'level_1_complete': 'நிலை 1 முடிந்தது',
      'claim_rewards_unlock_2': 'பரிசுகளைப் பெற்று நிலை 2-ஐத் திறக்கவும்',

      // Greeting & Profile Stats
      'greeting_hi': 'வணக்கம்',
      'total_xp': 'மொத்த XP',
      'coins': 'நாணயங்கள்',
      'stat_completed': 'முடிக்கப்பட்டது',
      'stat_badges': 'பதக்கங்கள்',
      'stat_collectibles': 'சேகரிப்புகள்',
      'stat_offline_sync': 'ஆஃப்லைன் ஒத்திசைவு',
      'ready': 'தயார்',
      'earned': 'பெறப்பட்டது',
      'unlocked': 'திறக்கப்பட்டது',
      'modules': 'தொகுதிகள்',
      'lessons': 'பாடங்கள்',
      'levels': 'நிலைகள்',
      'objectives_header': 'நோக்கங்கள்:',

      // Subjects & Modules
      'SCIENCE': 'அறிவியல்',
      'MATHEMATICS': 'கணிதம்',
      'CHEMISTRY': 'வேதியியல்',
      'PHYSICS': 'இயற்பியல்',
      'VIRTUAL LAB': 'மெய்நிகர் ஆய்வகம்',
      'mod_density_title': 'அடர்த்தி மற்றும் மிதப்புத்தன்மை',
      'mod_fractions_title': 'பின்னங்கள்',
      'mod_titration_title': 'அமில-கார டைட்ரேஷன்',
      'mod_ratios_title': 'விகிதம் மற்றும் விகிதாசாரம்',
      'mod_density_desc': 'திணிவு, கனஅளவு மற்றும் திரவங்களில் பொருட்களின் தன்மை பற்றிய இயற்பியலை ஆராயுங்கள்.',
      'mod_fractions_desc': 'முழுமையின் பகுதிகள், காட்சி பின்னங்கள் மற்றும் சமமான விகிதங்களில் தேர்ச்சி பெறுங்கள்.',
      'mod_titration_desc': 'நடுநிலையாக்கல் வினைகள், நிறங்காட்டிகள் மற்றும் துல்லியமான ஆய்வக அளவீடுகளில் தேர்ச்சி பெறுங்கள்.',

      // Badges, Shop & Collections
      'badge_explorer': 'ஆராய்ச்சியாளர்',
      'badge_scientist': 'விஞ்ஞானி',
      'badge_master': 'மேதை',
      'badge_champion': 'சாம்பியன்',
      'shop_buy': 'வாங்கு',
      'shop_owned': 'உள்ளது',
      'insufficient_coins_title': 'போதுமான நாணயங்கள் இல்லை',
      'purchase_successful_title': 'வாங்குதல் வெற்றிகரமாக முடிந்தது!',
      'already_owned_title': 'ஏற்கனவே சொந்தமானது',
      'rank_student_header': 'தரம் / மாணவர்',
      'total_score_header': 'மொத்த மதிப்பெண்',
    },
    'hi': {
      // Navigation & Dashboard
      'continue_learning': 'सीखना जारी रखें',
      'your_quest': 'आपकी खोज',
      'lesson_progress': 'पाठ {current} का {total}',
      'continue_quest': 'खोज जारी रखें',
      'start_quest': 'खोज शुरू करें',
      'revision': 'दोहराव',
      'quick_revision': 'त्वरित दोहराव',
      'concepts_ready': '{count} अवधारणाएं दोहराव के लिए तैयार',
      'start_revision': 'दोहराव शुरू करें',
      'my_modules': 'मेरे मॉड्यूल',
      'view_all': 'सभी देखें',
      'view_all_modules': 'सभी मॉड्यूल देखें',
      'leaderboard': 'लीडरबोर्ड',
      'your_class': 'आपकी कक्षा',
      'view_leaderboard': 'लीडरबोर्ड देखें',
      'collection': 'संग्रह',
      'shop': 'दुकान',
      'settings': 'सेटिंग्स',
      'profile': 'प्रोफाइल',
      'badges': 'बैज',
      'collectibles': 'संग्रहणीय वस्तुएं',
      'account': 'खाता',
      'logout': 'लॉग आउट',
      'language': 'भाषा',
      'sound': 'ध्वनि प्रभाव',
      'student_id': 'छात्र आईडी',
      'notifications': 'सूचनाएं',
      'quest_coins': 'क्वेस्ट सिक्के',
      'level': 'स्तर',
      'completed': 'पूरा हुआ',
      'current': 'वर्तमान',
      'locked': 'तालाबंद',
      'insufficient_coins': 'पर्याप्त सिक्के नहीं हैं! अधिक सिक्के कमाने के लिए सीखना जारी रखें।',
      'purchase_success': 'सफलतापूर्वक खरीदा गया!',
      'already_owned': 'आप पहले से ही इस वस्तु के मालिक हैं!',
      'start_module': 'मॉड्यूल शुरू करें',
      'continue_module': 'मॉड्यूल जारी रखें',
      'roadmap': 'मार्गदर्शन',
      'explore_modules': 'मॉड्यूल खोजें',
      'start_first_quest': 'अपनी पहली खोज शुरू करें',
      'quest_complete': 'खोज पूरी हुई!',
      'all_caught_up': 'सब कुछ पढ़ लिया गया है!',
      'change_language': 'भाषा बदलें',
      'home': 'होम',
      'back': 'पीछे',
      'close': 'बंद करें',

      // Missions
      'missions': 'मिशन',
      'daily_missions': 'दैनिक मिशन',
      'weekly_missions': 'साप्ताहिक मिशन',
      'daily': 'दैनिक',
      'weekly': 'साप्ताहिक',
      'resets_daily': 'प्रतिदिन मध्यरात्रि को रीसेट होता है',
      'resets_weekly': 'हर सोमवार को रीसेट होता है',
      'claim_reward_btn': 'इनाम प्राप्त करें!',
      'claimed_btn': 'प्राप्त किया',
      'complete_2_lessons': '2 पाठ पूरे करें',
      'earn_100_xp': '100 XP अर्जित करें',
      'finish_1_simulation_lab': '1 प्रयोगशाला सिमुलेशन पूरा करें',
      'master_1_full_module': '1 पूरा मॉड्यूल पूरा करें',
      'earn_500_weekly_xp': '500 साप्ताहिक XP अर्जित करें',
      'complete_any_2_curiosity_or_lab_lessons': 'कोई भी 2 पाठ या प्रयोगशाला सत्र पूरे करें',
      'gain_100_xp_from_quests_and_activities': 'खोजों और गतिविधियों से 100 XP प्राप्त करें',
      'conduct_any_phet_or_titration_lab_experiment': 'कोई भी PhET या अनुमापन प्रयोग करें',
      'finish_all_5_interactive_lessons_in_a_topic': 'एक विषय में सभी 5 पाठ पूरे करें',
      'gather_500_total_xp_across_the_entire_week': 'पूरे सप्ताह में कुल 500 XP एकत्र करें',

      // Daily Rewards
      'daily_login_reward': 'दैनिक लॉगिन इनाम',
      'day_streak': '{day}-दिन की लकीर',
      'streak_day': 'दिन {day}',
      'claim_reward': 'इनाम प्राप्त करें',
      'mystery_chest': 'रहस्यमय संदूक',
      'reward_claimed': 'इनाम प्राप्त हुआ!',
      'come_back_tomorrow': 'दिन {day} के इनाम के लिए कल वापस आएं!',
      'streak_complete': '7-दिन की लकीर पूरी हुई! अगला चक्र कल शुरू होगा।',
      'claimed': 'प्राप्त किया',

      // Ask Dendy
      'ask_dendy': 'डेंडी से पूछें',
      'dendy_companion': 'डेंडी एआई साथी',
      'ask_me_anything': 'विज्ञान या गणित के बारे में मुझसे कुछ भी पूछें!',
      'listening': 'सुन रहा है...',
      'tap_to_speak': 'बोलने के लिए माइक दबाएं या नीचे टाइप करें',
      'type_question': 'अपना प्रश्न टाइप करें...',
      'suggested_questions': 'सुझाए गए प्रश्न:',
      'why_wood_float': 'लकड़ी पानी में क्यों तैरती है?',
      'how_steel_ships_float': 'स्टील के जहाज कैसे तैरते हैं?',
      'why_ice_float': 'बर्फ क्यों तैरती है?',
      'what_is_density': 'घनत्व क्या है?',
      'what_is_titration': 'रसायन विज्ञान में अनुमापन क्या है?',
      'dendy_learning_fallback': 'मैं अभी सीख रहा हूँ! मेरा ऑफ़लाइन एआई भविष्य के संस्करण में इसका उत्तर देगा। मुझसे घनत्व, तैरना, उत्प्लावन या भिन्नों के बारे में पूछें!',

      // Dendy Dialogues & Mascots
      'ready_next_quest': 'अपनी अगली खोज के लिए तैयार हैं?',
      'almost_done_lesson': 'आप इस पाठ को लगभग पूरा कर चुके हैं!',
      'all_science_quests_complete': 'उत्कृष्ट! आपने सभी भौतिक विज्ञान प्रयोगशाला खोजों को पूरा कर लिया है!',
      'start_first_quest_desc': 'अपनी पहली खोज शुरू करें! आइए कुछ नया सीखें!',
      'investigate_reasons_lab': 'हम अगली प्रयोग प्रयोगशाला में सटीक कारणों और मापों की जांच करेंगे!',
      'discovery_complete': 'खोज पूरी हुई!',
      'predictions_tested': 'आपने अपने अनुमान लगाए और उनका परीक्षण किया।',
      'carefully_check_parameters': 'अपना उत्तर चुनने से पहले मापदंडों की सावधानीपूर्वक जांच करें!',
      'keep_trying_density_formula': 'प्रयास जारी रखें! घनत्व सूत्र के बारे में सोचें।',
      'lab_description': 'प्रयोगशाला विवरण',
      'titration_objectives': 'अनुमापन उद्देश्य',
      'apparatus_selection': '1. उपकरण चयन',
      'level_up': 'स्तर बढ़ा!',
      'reached_level': 'आप स्तर {level} पर पहुँच गए हैं!',
      'continue_adventure': 'साहसिक कार्य जारी रखें',
      'bonus_xp': 'बोनस XP',
      'rank_promoted': 'रैंक पदोन्नत',
      'fantastic_job_mastered': 'शानदार काम! आपने इस चुनौती में महारत हासिल की और पुरस्कार अर्जित किए।',
      'continue_next_lesson': 'अगले पाठ पर आगे बढ़ें',

      // Scientific Concepts
      'steel_ship_explanation': 'एक खोखला स्टील का जहाज तैरता है क्योंकि उसके अंदर फंसी हवा उसके कुल औसत घनत्व को कम कर देती है।',
      'ice_expands_title': 'बर्फ फैलती है और सामान्य ठोस पदार्थों से भिन्न होती है',
      'ice_expands_body': 'जमने पर पानी फैलता है, जिससे बर्फ का घनत्व 0.92 kg/L हो जाता है। इसीलिए बर्फ तैरती है।',
      'liquids_layer_title': 'तरल पदार्थ घनत्व के आधार पर स्वाभाविक रूप से परत बनाते हैं',
      'liquids_layer_body': 'जब अमिश्रणीय तरल पदार्थ मिलते हैं, तो हल्के तरल पदार्थ भारी तरल पदार्थों के ऊपर तैरते हैं।',
      'complete_and_unlock': 'पूरा करें और चुनौती अनलॉक करें',

      // Interactive Lessons (Discover Density & Buoyancy)
      'level_1_title': 'स्तर 1 • घनत्व की खोज करें',
      'lesson_counter': 'पाठ {current} का {total}',
      'curiosity': 'जिज्ञासा',
      'experiment': 'प्रयोग',
      'apply': 'लागू करें',
      'challenge': 'चुनौती',
      'teach_dendy': 'डेंडी को सिखाएं',
      'discovery_lab_step_1': 'खोज प्रयोगशाला • चरण 1',
      'discover_density': 'घनत्व की खोज करें',
      'why_objects_float_sink': '"कुछ वस्तुएं क्यों तैरती हैं जबकि अन्य डूब जाती हैं?"',
      'predict_before_test': 'परीक्षण से पहले, अनुमान लगाएं कि पानी में विभिन्न सामग्रियों को रखने पर क्या होगा। भौतिक परिणामों का अवलोकन करें।',
      'start_discovery': 'खोज शुरू करें',
      'predict_before_test_dendy': 'परीक्षण करने से पहले आइए एक अनुमान लगाएं!',
      'wooden_block': 'लकड़ी का टुकड़ा',
      'solid_oak_wood': 'ठोस ओक की लकड़ी',
      'metal_cube': 'धातु का घन',
      'solid_iron_steel': 'ठोस लोहा / स्टील',
      'plastic_ball': 'प्लास्टिक की गेंद',
      'hollow_plastic': 'खोखला हल्का प्लास्टिक',
      'river_stone': 'नदी का पत्थर',
      'dense_pebble': 'घना चिकना पत्थर',
      'apple': 'सेब',
      'fresh_fruit': 'ताज़ा फल',
      'float': 'तैरना',
      'sink': 'डूबना',
      'test_hypothesis': 'अनुमान का परीक्षण करें',
      'water_tank_lab': 'पानी की टंकी प्रयोगशाला',
      'tap_to_test': 'परीक्षण करने के लिए वस्तु पर टैप करें',
      'what_did_you_observe': 'आपने क्या देखा?',
      'reflection_wood_plastic_float': 'लकड़ी और प्लास्टिक तैरते हैं क्योंकि उनका घनत्व पानी से कम होता है। धातु और पत्थर डूबते हैं क्योंकि वे अधिक घने होते हैं।',
      'reflection_heavy_sink': 'भारी वस्तुएं हमेशा डूबती हैं और हल्की वस्तुएं हमेशा तैरती हैं।',
      'reflection_shape_only': 'आकार ही एकमात्र कारण है जिससे वस्तुएं तैरती हैं।',
      'continue_to_lesson_2': 'पाठ 2 पर आगे बढ़ें',
      'lesson_2_measure_density': 'पाठ 2: घनत्व मापें',
      'lesson_2_title_progress': 'पाठ 2 का 5',
      'mass_volume_lab': 'द्रव्यमान और आयतन प्रयोगशाला',
      'change_mass_volume_desc': 'वास्तविक समय में घनत्व बदलते देखने के लिए द्रव्यमान और आयतन बदलें!',
      'mass_kg': 'द्रव्यमान (kg)',
      'volume_l': 'आयतन (L)',
      'density_formula_desc': 'घनत्व = द्रव्यमान ÷ आयतन',
      'water_density_standard': 'पानी का घनत्व: 1.00 kg/L',
      'reset_lab': 'रीसेट करें',
      'nice_prediction_become_scientists': 'शानदार भविष्यवाणी! अब आइए वैज्ञानिक बनें।',
      'lets_experiment': 'आइए प्रयोग करें।',
      'try_making_object_heavier': 'इस वस्तु को और भारी बनाने का प्रयास करें।',
      'what_changed': 'क्या बदला?',
      'sank_deeper': 'अधिक गहरा डूब गया',
      'floated_higher': 'ऊपर तैरने लगा',
      'nothing_changed': 'कुछ नहीं बदला',
      'what_happens_change_size': 'यदि हम इसके आकार को बदलें तो क्या होगा?',
      'what_do_you_notice': 'आपने क्या देखा?',
      'compare_two_objects': 'अब आइए टंकी में दो वस्तुओं की अगल-बगल तुलना करें।',
      'which_one_sinks_more': 'कौन सी वस्तु अधिक डूबती है?',
      'denser_heavier_object': 'अधिक घनी वस्तु',
      'larger_lighter_object': 'हल्की वस्तु',
      'both_sink_equally': 'दोनों समान रूप से डूबती हैं',
      'compare_mode': 'तुलना मोड',
      'single_mode': 'एकल वस्तु',
      'object_a': 'वस्तु A',
      'object_b': 'वस्तु B',
      'mat_wood': 'लकड़ी',
      'mat_ice': 'बर्फ',
      'mat_plastic': 'प्लास्टिक',
      'mat_steel': 'स्टील',
      'mat_gold': 'सोना',
      'youve_changed_mass': 'आपने द्रव्यमान बदल दिया।',
      'youve_changed_volume': 'आपने आयतन बदल दिया।',
      'can_you_spot_pattern': 'क्या आप नियम या पैटर्न पहचान सकते हैं?',
      'the_density_formula': 'घनत्व का सूत्र',
      'density_equals_mass_divided_volume': 'घनत्व = द्रव्यमान ÷ आयतन',
      'density_discovery_desc': 'जब समान आयतन में द्रव्यमान बढ़ता है, तो घनत्व बढ़ता है। जब समान द्रव्यमान का आयतन बढ़ता है, तो घनत्व घटता है!',
      'less_dense_than_water_floats': 'पानी से कम घना (< 1.00 kg/L) = तैरता है!',
      'more_dense_than_water_sinks': 'पानी से अधिक घना (> 1.00 kg/L) = डूबता है!',
      'continue_to_lesson_3': 'पाठ 3 पर आगे बढ़ें',
      'lesson_3_real_world': 'पाठ 3: वास्तविक दुनिया का घनत्व',
      'apply_your_knowledge': 'अपने ज्ञान को लागू करें',
      'why_steel_ships_float_q': 'विशाल स्टील के जहाज पानी पर क्यों तैरते हैं?',
      'why_ice_floats_q': 'बर्फ पानी पर क्यों तैरती है?',
      'why_oil_floats_q': 'तेल पानी पर क्यों तैरता है?',
      'lesson_4_detective': 'पाठ 4: घनत्व जासूस',
      'mystery_objects': 'रहस्यमयी वस्तुएं',
      'identify_gold_desc': 'घनत्व के आधार पर पहचानें कि कौन सी वस्तु सोने से बनी है!',
      'submit_answer': 'उत्तर सबमिट करें',
      'lesson_5_teach_dendy': 'पाठ 5: डेंडी को सिखाएं',
      'explain_density_dendy': 'द्रव्यमान और आयतन का उपयोग करके डेंडी को समझाएं कि वस्तुएं क्यों तैरती या डूबती हैं!',
      'density_mastered': 'घनत्व में महारत हासिल की',
      'level_1_complete': 'स्तर 1 पूरा हुआ',
      'claim_rewards_unlock_2': 'इनाम प्राप्त करें और स्तर 2 अनलॉक करें',

      // Greeting & Profile Stats
      'greeting_hi': 'नमस्ते',
      'total_xp': 'कुल XP',
      'coins': 'सिक्के',
      'stat_completed': 'पूरा हुआ',
      'stat_badges': 'बैज',
      'stat_collectibles': 'संग्रहणीय वस्तुएं',
      'stat_offline_sync': 'ऑफ़लाइन सिंक',
      'ready': 'तैयार',
      'earned': 'अर्जित',
      'unlocked': 'अनलॉक किया गया',
      'modules': 'मॉड्यूल',
      'lessons': 'पाठ',
      'levels': 'स्तर',
      'objectives_header': 'उद्देश्य:',

      // Subjects & Modules
      'SCIENCE': 'विज्ञान',
      'MATHEMATICS': 'गणित',
      'CHEMISTRY': 'रसायन विज्ञान',
      'PHYSICS': 'भौतिकी',
      'VIRTUAL LAB': 'आभासी प्रयोगशाला',
      'mod_density_title': 'घनत्व और उत्प्लावन',
      'mod_fractions_title': 'भिन्न',
      'mod_titration_title': 'अम्ल-क्षार अनुमापन',
      'mod_ratios_title': 'अनुपात और समानुपात',
      'mod_density_desc': 'द्रव्यमान, आयतन और तरल पदार्थों में सामग्रियों के व्यवहार के भौतिकी का अन्वेषण करें।',
      'mod_fractions_desc': 'संपूर्ण के भागों, दृश्य भिन्नों और समतुल्य अनुपातों में महारत हासिल करें।',
      'mod_titration_desc': 'उदासीनीकरण प्रतिक्रियाओं, संकेतकों और सटीक प्रयोगशाला मापों में महारत हासिल करें।',

      // Badges, Shop & Collections
      'badge_explorer': 'अन्वेषक',
      'badge_scientist': 'वैज्ञानिक',
      'badge_master': 'मास्टर',
      'badge_champion': 'चैंपियन',
      'shop_buy': 'खरीदें',
      'shop_owned': 'स्वामित्व में',
      'insufficient_coins_title': 'अपर्याप्त सिक्के',
      'purchase_successful_title': 'खरीद सफल रही!',
      'already_owned_title': 'पहले से स्वामित्व में है',
      'rank_student_header': 'रैंक / छात्र',
      'total_score_header': 'कुल अंक',
    },
    'or': {
      // Navigation & Dashboard
      'continue_learning': 'ଶିଖିବା ଜାରି ରଖନ୍ତୁ',
      'your_quest': 'ଆପଣଙ୍କର ଅଭିଯାନ',
      'lesson_progress': 'ପାଠ {current} ରୁ {total}',
      'continue_quest': 'ଅଭିଯାନ ଜାରି ରଖନ୍ତୁ',
      'start_quest': 'ଅଭିଯାନ ଆରମ୍ଭ କରନ୍ତୁ',
      'revision': 'ପୁନରାବୃତ୍ତି',
      'quick_revision': 'ଦ୍ରୁତ ପୁନରାବୃତ୍ତି',
      'concepts_ready': '{count} ଟି ଧାରଣା ପୁନରାବୃତ୍ତି ପାଇଁ ପ୍ରସ୍ତୁତ',
      'start_revision': 'ପୁନରାବୃତ୍ତି ଆରମ୍ଭ କରନ୍ତୁ',
      'my_modules': 'ମୋର ମଡ୍ୟୁଲ୍',
      'view_all': 'ସମସ୍ତ ଦେଖନ୍ତୁ',
      'view_all_modules': 'ସମସ୍ତ ମଡ୍ୟୁଲ୍ ଦେଖନ୍ତୁ',
      'leaderboard': 'ଶ୍ରେଷ୍ଠ ତାଲିକା',
      'your_class': 'ଆପଣଙ୍କ ଶ୍ରେଣୀ',
      'view_leaderboard': 'ଶ୍ରେଷ୍ଠ ତାଲିକା ଦେଖନ୍ତୁ',
      'collection': 'ସଂଗ୍ରହ',
      'shop': 'ଦୋକାନ',
      'settings': 'ସେଟିଂସ୍',
      'profile': 'ପ୍ରୋଫାଇଲ୍',
      'badges': 'ବ୍ୟାଜ୍',
      'collectibles': 'ସଂଗ୍ରହଣୀୟ ବସ୍ତୁ',
      'account': 'ଖାତା',
      'logout': 'ଲଗ୍ ଆଉଟ୍',
      'language': 'ଭାଷା',
      'sound': 'ଶବ୍ଦ ପ୍ରଭାବ',
      'student_id': 'ଛାତ୍ର ଆଇଡି',
      'notifications': 'ବିଜ୍ଞପ୍ତି',
      'quest_coins': 'କ୍ୱେଷ୍ଟ୍ କଏନ୍',
      'level': 'ସ୍ତର',
      'completed': 'ସମ୍ପୂର୍ଣ୍ଣ ହୋଇଛି',
      'current': 'ବର୍ତ୍ତମାନ',
      'locked': 'ତାଲା ପଡିଛି',
      'insufficient_coins': 'ଯଥେଷ୍ଟ କଏନ୍ ନାହିଁ! ଅଧିକ ପାଇବା ପାଇଁ ଶିଖନ୍ତୁ।',
      'purchase_success': 'ସଫଳତାର ସହ କିଣାଗଲା!',
      'already_owned': 'ଆପଣ ଏହା ପୂର୍ବରୁ କିଣିସାରିଛନ୍ତି!',
      'start_module': 'ମଡ୍ୟୁଲ୍ ଆରମ୍ଭ କରନ୍ତୁ',
      'continue_module': 'ମଡ୍ୟୁଲ୍ ଜାରି ରଖନ୍ତୁ',
      'roadmap': 'ପଥଚିତ୍ର',
      'explore_modules': 'ମଡ୍ୟୁଲ୍ ଅନ୍ୱେଷଣ କରନ୍ତୁ',
      'start_first_quest': 'ପ୍ରଥମ ଅଭିଯାନ ଆରମ୍ଭ କରନ୍ତୁ',
      'quest_complete': 'ଅଭିଯାନ ସମ୍ପୂର୍ଣ୍ଣ!',
      'all_caught_up': 'ଆପଣ ସବୁକିଛି ପଢ଼ି ସାରିଛନ୍ତି!',
      'change_language': 'ଭାଷା ବଦଳାନ୍ତୁ',
      'home': 'ମୁଖ୍ୟ ପୃଷ୍ଠା',
      'back': 'ପଛକୁ',
      'close': 'ବନ୍ଦ କରନ୍ତୁ',

      // Missions
      'missions': 'ଲକ୍ଷ୍ୟ',
      'daily_missions': 'ଦୈନିକ ଲକ୍ଷ୍ୟ',
      'weekly_missions': 'ସାପ୍ତାହିକ ଲକ୍ଷ୍ୟ',
      'daily': 'ଦୈନିକ',
      'weekly': 'ସାପ୍ତାହିକ',
      'resets_daily': 'ପ୍ରତିଦିନ ମଧ୍ୟରାତ୍ରିରେ ରିସେଟ୍ ହୁଏ',
      'resets_weekly': 'ପ୍ରତି ସୋମବାର ରିସେଟ୍ ହୁଏ',
      'claim_reward_btn': 'ପୁରସ୍କାର ନିଅନ୍ତୁ!',
      'claimed_btn': 'ଗ୍ରହଣ କରାଗଲା',
      'complete_2_lessons': '୨ ଟି ପାଠ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ',
      'earn_100_xp': '୧୦୦ XP ଅର୍ଜନ କରନ୍ତୁ',
      'finish_1_simulation_lab': '୧ ଟି ପରୀକ୍ଷାଗାର ଶେଷ କରନ୍ତୁ',
      'master_1_full_module': '୧ ଟି ସମ୍ପୂର୍ଣ୍ଣ ମଡ୍ୟୁଲ୍ ଶିଖନ୍ତୁ',
      'earn_500_weekly_xp': 'ସପ୍ତାହରେ ୫୦୦ XP ଅର୍ଜନ କରନ୍ତୁ',
      'complete_any_2_curiosity_or_lab_lessons': 'ଯେକୌଣସି ୨ ଟି କୌତୂହଳ କିମ୍ବା ଲ୍ୟାବ୍ ପାଠ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ',
      'gain_100_xp_from_quests_and_activities': 'ଅଭିଯାନରୁ ୧୦୦ XP ପ୍ରାପ୍ତ କରନ୍ତୁ',
      'conduct_any_phet_or_titration_lab_experiment': 'ଯେକୌଣସି PhET କିମ୍ବା ଟାଇଟ୍ରେସନ୍ ପରୀକ୍ଷା କରନ୍ତୁ',
      'finish_all_5_interactive_lessons_in_a_topic': 'ଏକ ବିଷୟର ସମସ୍ତ ୫ ଟି ପାଠ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ',
      'gather_500_total_xp_across_the_entire_week': 'ସପ୍ତାହରେ ସମୁଦାୟ ୫୦୦ XP ସଂଗ୍ରହ କରନ୍ତୁ',

      // Daily Rewards
      'daily_login_reward': 'ଦୈନିକ ଲଗଇନ୍ ପୁରସ୍କାର',
      'day_streak': '{day}-ଦିନ ଲଗାତାର',
      'streak_day': 'ଦିନ {day}',
      'claim_reward': 'ପୁରସ୍କାର ନିଅନ୍ତୁ',
      'mystery_chest': 'ରହସ୍ୟମୟ ବାକ୍ସ',
      'reward_claimed': 'ପୁରସ୍କାର ମିଳିଗଲା!',
      'come_back_tomorrow': 'ଦିନ {day} ପୁରସ୍କାର ପାଇଁ ଆସନ୍ତାକାଲି ଆସନ୍ତୁ!',
      'streak_complete': '୭-ଦିନ ସମ୍ପୂର୍ଣ୍ଣ ହେଲା! ପରବର୍ତ୍ତୀ ଚକ୍ର ଆସନ୍ତାକାଲି ଆରମ୍ଭ ହେବ।',
      'claimed': 'ମିଳିଗଲା',

      // Ask Dendy
      'ask_dendy': 'ଡେଣ୍ଡିକୁ ପଚାରନ୍ତୁ',
      'dendy_companion': 'ଡେଣ୍ଡି AI ସାଥୀ',
      'ask_me_anything': 'ବିଜ୍ଞାନ କିମ୍ବା ଗଣିତ ବିଷୟରେ ମୋତେ ଯାହା ଇଚ୍ଛା ପଚାରନ୍ତୁ!',
      'listening': 'ଶୁଣୁଛି...',
      'tap_to_speak': 'କହିବା ପାଇଁ ମାଇକ୍ ଦବାନ୍ତୁ କିମ୍ବା ଟାଇପ୍ କରନ୍ତୁ',
      'type_question': 'ଆପଣଙ୍କର ପ୍ରଶ୍ନ ଲେଖନ୍ତୁ...',
      'suggested_questions': 'ପ୍ରସ୍ତାବିତ ପ୍ରଶ୍ନଗୁଡ଼ିକ:',
      'why_wood_float': 'କାଠ ପାଣିରେ କାହିଁକି ଭାସେ?',
      'how_steel_ships_float': 'ଷ୍ଟିଲ୍ ଜାହାଜ କିପରି ଭାସେ?',
      'why_ice_float': 'ବରଫ କାହିଁକି ଭାସେ?',
      'what_is_density': 'ସାନ୍ଦ୍ରତା କ’ଣ?',
      'what_is_titration': 'ରସାୟନ ବିଜ୍ଞାନରେ ଟାଇଟ୍ରେସନ୍ କ’ଣ?',
      'dendy_learning_fallback': 'ମୁଁ ଏବେ ବି ଶିଖୁଛି! ମୋର ଅଫଲାଇନ୍ AI ପରବର୍ତ୍ତୀ ସଂସ୍କରଣରେ ଏହାର ଉତ୍ତର ଦେବ। ମୋତେ ସାନ୍ଦ୍ରତା, ଭାସିବା, ଟାଇଟ୍ରେସନ୍ କିମ୍ବା ଭଗ୍ନାଂଶ ବିଷୟରେ ପଚାରନ୍ତୁ!',

      // Dendy Dialogues & Mascots
      'ready_next_quest': 'ଆପଣଙ୍କର ପରବର୍ତ୍ତୀ ଅଭିଯାନ ପାଇଁ ପ୍ରସ୍ତୁତ ତ?',
      'almost_done_lesson': 'ଆପଣ ପ୍ରାୟତଃ ଏହି ପାଠ ଶେଷ କରିସାରିଛନ୍ତି!',
      'all_science_quests_complete': 'ବହୁତ ବଢ଼ିଆ! ଆପଣ ସମସ୍ତ ପଦାର୍ଥ ବିଜ୍ଞାନ ଲ୍ୟାବ୍ ଅଭିଯାନ ସମ୍ପୂର୍ଣ୍ଣ କରିଛନ୍ତି!',
      'start_first_quest_desc': 'ଆପଣଙ୍କର ପ୍ରଥମ ଅଭିଯାନ ଆରମ୍ଭ କରନ୍ତୁ! ଆସନ୍ତୁ କିଛି ନୂଆ ଶିଖିବା!',
      'investigate_reasons_lab': 'ଆମେ ପରବର୍ତ୍ତୀ ପରୀକ୍ଷାଗାରରେ ସଠିକ୍ କାରଣ ଏବଂ ମାପ ଅନୁସନ୍ଧାନ କରିବା!',
      'discovery_complete': 'ଆବିଷ୍କାର ସମ୍ପୂର୍ଣ୍ଣ ହେଲା!',
      'predictions_tested': 'ଆପଣ ଆପଣଙ୍କର ଅନୁମାନ କଲେ ଏବଂ ତାହା ପରୀକ୍ଷା କଲେ।',
      'carefully_check_parameters': 'ଉତ୍ତର ବାଛିବା ପୂର୍ବରୁ ମାନଗୁଡ଼ିକୁ ଭଲଭାବେ ଯାଞ୍ଚ କରନ୍ତୁ!',
      'keep_trying_density_formula': 'ଚେଷ୍ଟା ଜାରି ରଖନ୍ତୁ! ସାନ୍ଦ୍ରତା ସୂତ୍ର ବିଷୟରେ ଚିନ୍ତା କରନ୍ତୁ।',
      'lab_description': 'ପରୀକ୍ଷାଗାର ବିବରଣୀ',
      'titration_objectives': 'ଟାଇଟ୍ରେସନ୍ ଉଦ୍ଦେଶ୍ୟ',
      'apparatus_selection': '୧. ଉପକରଣ ଚୟନ',
      'level_up': 'ସ୍ତର ବୃଦ୍ଧି ପାଇଲା!',
      'reached_level': 'ଆପଣ ସ୍ତର {level} ରେ ପହଞ୍ଚିଗଲେ!',
      'continue_adventure': 'ଯାତ୍ରା ଜାରି ରଖନ୍ତୁ',
      'bonus_xp': 'ବୋନସ୍ XP',
      'rank_promoted': 'ପଦୋନ୍ନତି ପାଇଲେ',
      'fantastic_job_mastered': 'ଚମତ୍କାର! ଆପଣ ଏହି ଚ୍ୟାଲେଞ୍ଜ ଜିତି ପୁରସ୍କାର ପାଇଲେ।',
      'continue_next_lesson': 'ପରବର୍ତ୍ତୀ ପାଠକୁ ଯାଆନ୍ତୁ',

      // Scientific Concepts
      'steel_ship_explanation': 'ଏକ ଫମ୍ପା ଷ୍ଟିଲ୍ ଜାହାଜ ଭାସେ କାରଣ ଏହା ଭିତରେ ଥିବା ବାୟୁ ଏହାର ହାରାହାରି ସାନ୍ଦ୍ରତାକୁ ୧.୦୦ kg/L ରୁ କମ୍ କରିଦିଏ।',
      'ice_expands_title': 'ବରଫ ପ୍ରସାରିତ ହୁଏ ଏବଂ ସାଧାରଣ କଠିନ ପଦାର୍ଥଠାରୁ ଭିନ୍ନ ହୁଏ',
      'ice_expands_body': 'ଜମାଟ ବାନ୍ଧିବା ସମୟରେ ପାଣି ପ୍ରସାରିତ ହୁଏ, ଯାହା ବରଫର ସାନ୍ଦ୍ରତାକୁ ୦.୯୨ kg/L କରିଦିଏ। ସେଥିପାଇଁ ବରଫ ଭାସେ।',
      'liquids_layer_title': 'ତରଳ ପଦାର୍ଥ ସାନ୍ଦ୍ରତା ଅନୁସାରେ ସ୍ତର ସୃଷ୍ଟି କରେ',
      'liquids_layer_body': 'ଯେତେବେଳେ ଦୁଇଟି ତରଳ ମିଶନ୍ତି ନାହିଁ, ହାଲୁକା ତରଳ ଗୁଡ଼ିକ ଭାରୀ ତରଳ ଉପରେ ଭାସନ୍ତି।',
      'complete_and_unlock': 'ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ ଏବଂ ଅନଲକ୍ କରନ୍ତୁ',

      // Interactive Lessons (Discover Density & Buoyancy)
      'level_1_title': 'ସ୍ତର ୧ • ସାନ୍ଦ୍ରତା ଆବିଷ୍କାର କରନ୍ତୁ',
      'lesson_counter': 'ପାଠ {current} ରୁ {total}',
      'curiosity': 'କୌତୂହଳ',
      'experiment': 'ପରୀକ୍ଷା',
      'apply': 'ପ୍ରୟୋଗ',
      'challenge': 'ଚ୍ୟାଲେଞ୍ଜ',
      'teach_dendy': 'ଡେଣ୍ଡିକୁ ଶିଖାନ୍ତୁ',
      'discovery_lab_step_1': 'ଆବିଷ୍କାର ଲ୍ୟାବ୍ • ପଦକ୍ଷେପ ୧',
      'discover_density': 'ସାନ୍ଦ୍ରତା ଆବିଷ୍କାର କରନ୍ତୁ',
      'why_objects_float_sink': '"କିଛି ବସ୍ତୁ କାହିଁକି ଭାସେ ଏବଂ ଅନ୍ୟଗୁଡ଼ିକ କାହିଁକି ବୁଡ଼ିଯାଏ?"',
      'predict_before_test': 'ପରୀକ୍ଷା କରିବା ପୂର୍ବରୁ ଅନୁମାନ କରନ୍ତୁ ଯେ ବିଭିନ୍ନ ପଦାର୍ଥ ପାଣିରେ ପକାଇଲେ କ’ଣ ହେବ। ପରିଣାମ ଦେଖନ୍ତୁ।',
      'start_discovery': 'ଆବିଷ୍କାର ଆରମ୍ଭ କରନ୍ତୁ',
      'predict_before_test_dendy': 'ପରୀକ୍ଷା କରିବା ପୂର୍ବରୁ ଆସନ୍ତୁ ଗୋଟିଏ ଅନୁମାନ ଲଗାଇବା!',
      'wooden_block': 'କାଠ ଖଣ୍ଡ',
      'solid_oak_wood': 'ନିଦା ଓକ୍ କାଠ',
      'metal_cube': 'ଧାତବ ଘନକ',
      'solid_iron_steel': 'ନିଦା ଲୁହା / ଷ୍ଟିଲ୍',
      'plastic_ball': 'ପ୍ଲାଷ୍ଟିକ୍ ବଲ୍',
      'hollow_plastic': 'ଫମ୍ପା ହାଲୁକା ପ୍ଲାଷ୍ଟିକ୍',
      'river_stone': 'ନଦୀ ପଥର',
      'dense_pebble': 'ଚିକ୍କଣ ନିଦା ପଥର',
      'apple': 'ସେଓ',
      'fresh_fruit': 'ତାଜା ଫଳ',
      'float': 'ଭାସିବା',
      'sink': 'ବୁଡ଼ିବା',
      'test_hypothesis': 'ଅନୁମାନ ପରୀକ୍ଷା କରନ୍ତୁ',
      'water_tank_lab': 'ପାଣି ଟାଙ୍କି ଲ୍ୟାବ୍',
      'tap_to_test': 'ପରୀକ୍ଷା କରିବା ପାଇଁ ବସ୍ତୁ ଉପରେ ଟ୍ୟାପ୍ କରନ୍ତୁ',
      'what_did_you_observe': 'ଆପଣ କ’ଣ ଲକ୍ଷ୍ୟ କଲେ?',
      'reflection_wood_plastic_float': 'କାଠ ଏବଂ ପ୍ଲାଷ୍ଟିକ୍ ଭାସେ କାରଣ ସେମାନଙ୍କର ସାନ୍ଦ୍ରତା ପାଣିଠାରୁ କମ୍। ଧାତୁ ଏବଂ ପଥର ବୁଡ଼ିଯାଏ କାରଣ ସେମାନେ ଅଧିକ ସାନ୍ଦ୍ର।',
      'reflection_heavy_sink': 'ଭାରୀ ଜିନିଷ ସବୁବେଳେ ବୁଡ଼ିଯାଏ ଏବଂ ହାଲୁକା ଜିନିଷ ସବୁବେଳେ ଭାସେ।',
      'reflection_shape_only': 'ଆକାର ହିଁ ବସ୍ତୁ ଭାସିବାର ଏକମାତ୍ର କାରଣ।',
      'continue_to_lesson_2': 'ପାଠ ୨ କୁ ଯାଆନ୍ତୁ',
      'lesson_2_measure_density': 'ପାଠ ୨: ସାନ୍ଦ୍ରତା ମାପନ୍ତୁ',
      'lesson_2_title_progress': 'ପାଠ ୨ ରୁ ୫',
      'mass_volume_lab': 'ବସ୍ତୁତ୍ୱ ଏବଂ ଆୟତନ ଲ୍ୟାବ୍',
      'change_mass_volume_desc': 'ସାନ୍ଦ୍ରତା ପରିବର୍ତ୍ତନ ଦେଖିବା ପାଇଁ ବସ୍ତୁତ୍ୱ ଏବଂ ଆୟତନ ବଦଳାନ୍ତୁ!',
      'mass_kg': 'ବସ୍ତୁତ୍ୱ (kg)',
      'volume_l': 'ଆୟତନ (L)',
      'density_formula_desc': 'ସାନ୍ଦ୍ରତା = ବସ୍ତୁତ୍ୱ ÷ ଆୟତନ',
      'water_density_standard': 'ପାଣିର ସାନ୍ଦ୍ରତା: ୧.୦୦ kg/L',
      'reset_lab': 'ରିସେଟ୍ କରନ୍ତୁ',
      'nice_prediction_become_scientists': 'ଉତ୍ତମ ପୂର୍ବାନୁମାନ! ଆସନ୍ତୁ ଏବେ ବୈଜ୍ଞାନିକ ହେବା।',
      'lets_experiment': 'ଆସନ୍ତୁ ପରୀକ୍ଷଣ କରିବା।',
      'try_making_object_heavier': 'ଏହି ବସ୍ତୁକୁ ଅଧିକ ଭାରୀ କରିବାକୁ ଚେଷ୍ଟା କରନ୍ତୁ।',
      'what_changed': 'କ’ଣ ପରିବର୍ତ୍ତନ ହେଲା?',
      'sank_deeper': 'ଅଧିକ ଗଭୀରକୁ ବୁଡ଼ିଗଲା',
      'floated_higher': 'ଉପରକୁ ଭାସିଲା',
      'nothing_changed': 'କିଛି ବଦଳିଲା ନାହିଁ',
      'what_happens_change_size': 'ଆକାର ବଦଳାଇଲେ କ’ଣ ହେବ?',
      'what_do_you_notice': 'ଆପଣ କ’ଣ ଲକ୍ଷ୍ୟ କରୁଛନ୍ତି?',
      'compare_two_objects': 'ଏବେ ଆସନ୍ତୁ ଟାଙ୍କିରେ ଦୁଇଟି ବସ୍ତୁକୁ ପାଖାପାଖି ତୁଳନା କରିବା।',
      'which_one_sinks_more': 'କେଉଁଟି ଅଧିକ ବୁଡ଼ୁଛି?',
      'denser_heavier_object': 'ଅଧିକ ସାନ୍ଦ୍ର ବସ୍ତୁ',
      'larger_lighter_object': 'ହାଲୁକା ବସ୍ତୁ',
      'both_sink_equally': 'ଉଭୟ ସମାନ ଭାବରେ ବୁଡ଼ୁଛନ୍ତି',
      'compare_mode': 'ତୁଳନା ମୋଡ୍',
      'single_mode': 'ଏକକ ବସ୍ତୁ',
      'object_a': 'ବସ୍ତୁ A',
      'object_b': 'ବସ୍ତୁ B',
      'mat_wood': 'କାଠ',
      'mat_ice': 'ବରଫ',
      'mat_plastic': 'ପ୍ଲାଷ୍ଟିକ୍',
      'mat_steel': 'ଷ୍ଟିଲ୍',
      'mat_gold': 'ସୁନା',
      'youve_changed_mass': 'ଆପଣ ବସ୍ତୁତ୍ୱ ବଦଳାଇଲେ।',
      'youve_changed_volume': 'ଆପଣ ଆୟତନ ବଦଳାଇଲେ।',
      'can_you_spot_pattern': 'ଆପଣ ନିୟମ କିମ୍ବା ପାଟର୍ନ ଚିହ୍ନିପାରୁଛନ୍ତି କି?',
      'the_density_formula': 'ସାନ୍ଦ୍ରତା ସୂତ୍ର',
      'density_equals_mass_divided_volume': 'ସାନ୍ଦ୍ରତା = ବସ୍ତୁତ୍ୱ ÷ ଆୟତନ',
      'density_discovery_desc': 'ସମାନ ଆୟତନରେ ବସ୍ତୁତ୍ୱ ବଢ଼ିଲେ ସାନ୍ଦ୍ରତା ବଢ଼େ। ସମାନ ବସ୍ତୁତ୍ୱର ଆୟତନ ବଢ଼ିଲେ ସାନ୍ଦ୍ରତା କମିଯାଏ!',
      'less_dense_than_water_floats': 'ପାଣିଠାରୁ କମ୍ ସାନ୍ଦ୍ର (< ୧.୦୦ kg/L) = ଭାସେ!',
      'more_dense_than_water_sinks': 'ପାଣିଠାରୁ ଅଧିକ ସାନ୍ଦ୍ର (> ୧.୦୦ kg/L) = ବୁଡ଼େ!',
      'continue_to_lesson_3': 'ପାଠ ୩ କୁ ଯାଆନ୍ତୁ',
      'lesson_3_real_world': 'ପାଠ ୩: ବାସ୍ତବ ଦୁନିଆର ସାନ୍ଦ୍ରତା',
      'apply_your_knowledge': 'ଆପଣଙ୍କର ଜ୍ଞାନ ପ୍ରୟୋଗ କରନ୍ତୁ',
      'why_steel_ships_float_q': 'ବଡ଼ ବଡ଼ ଷ୍ଟିଲ୍ ଜାହାଜ ପାଣିରେ କାହିଁକି ଭାସେ?',
      'why_ice_floats_q': 'ବରଫ ପାଣିରେ କାହିଁକି ଭାସେ?',
      'why_oil_floats_q': 'ତେଲ ପାଣିରେ କାହିଁକି ଭାସେ?',
      'lesson_4_detective': 'ପାଠ ୪: ସାନ୍ଦ୍ରତା ଗୋଇନ୍ଦା',
      'mystery_objects': 'ରହସ୍ୟମୟ ବସ୍ତୁଗୁଡ଼ିକ',
      'identify_gold_desc': 'ସାନ୍ଦ୍ରତା ଆଧାରରେ କେଉଁ ବସ୍ତୁ ସୁନାରେ ତିଆରି ଚିହ୍ନଟ କରନ୍ତୁ!',
      'submit_answer': 'ଉତ୍ତର ଦାଖଲ କରନ୍ତୁ',
      'lesson_5_teach_dendy': 'ପାଠ ୫: ଡେଣ୍ଡିକୁ ଶିଖାନ୍ତୁ',
      'explain_density_dendy': 'ବସ୍ତୁତ୍ୱ ଏବଂ ଆୟତନ ବ୍ୟବହାର କରି ଡେଣ୍ଡିକୁ ବୁଝାନ୍ତୁ କାହିଁକି ବସ୍ତୁ ଭାସେ କିମ୍ବା ବୁଡ଼ିଯାଏ!',
      'density_mastered': 'ସାନ୍ଦ୍ରତା ସମ୍ପୂର୍ଣ୍ଣ ହେଲା',
      'level_1_complete': 'ସ୍ତର ୧ ସମ୍ପୂର୍ଣ୍ଣ',
      'claim_rewards_unlock_2': 'ପୁରସ୍କାର ନିଅନ୍ତୁ ଏବଂ ସ୍ତର ୨ ଅନଲକ୍ କରନ୍ତୁ',

      // Greeting & Profile Stats
      'greeting_hi': 'ନମସ୍କାର',
      'total_xp': 'ମୋଟ XP',
      'coins': 'ମୁଦ୍ରା',
      'stat_completed': 'ସମ୍ପୂର୍ଣ୍ଣ',
      'stat_badges': 'ବ୍ୟାଜ୍',
      'stat_collectibles': 'ସଂଗ୍ରହଣୀୟ',
      'stat_offline_sync': 'ଅଫଲାଇନ୍ ସିଙ୍କ୍',
      'ready': 'ପ୍ରସ୍ତୁତ',
      'earned': 'ଅର୍ଜିତ',
      'unlocked': 'ଅନଲକ୍',
      'modules': 'ମଡ୍ୟୁଲ୍',
      'lessons': 'ପାଠ',
      'levels': 'ସ୍ତର',
      'objectives_header': 'ଉଦ୍ଦେଶ୍ୟ:',

      // Subjects & Modules
      'SCIENCE': 'ବିଜ୍ଞାନ',
      'MATHEMATICS': 'ଗଣିତ',
      'CHEMISTRY': 'ରସାୟନ ବିଜ୍ଞାନ',
      'PHYSICS': 'ପଦାର୍ଥ ବିଜ୍ଞାନ',
      'VIRTUAL LAB': 'ଭର୍ଚୁଆଲ୍ ଲ୍ୟାବ୍',
      'mod_density_title': 'ସାନ୍ଦ୍ରତା ଏବଂ ଭାସମାନତା',
      'mod_fractions_title': 'ଭଗ୍ନାଂଶ',
      'mod_titration_title': 'ଅମ୍ଳ-କ୍ଷାର ଟାଇଟ୍ରେସନ୍',
      'mod_ratios_title': 'ଅନୁପାତ ଏବଂ ସମାନୁପାତ',
      'mod_density_desc': 'ବସ୍ତୁତ୍ୱ, ଆୟତନ ଏବଂ ତରଳ ପଦାର୍ଥରେ ବସ୍ତୁର ଆଚରଣ ବିଷୟରେ ଜାଣନ୍ତୁ।',
      'mod_fractions_desc': 'ସମଗ୍ରର ଅଂଶ, ଦୃଶ୍ୟମାନ ଭଗ୍ନାଂଶ ଏବଂ ସମତୁଲ ଅନୁପାତ ଶିଖନ୍ତୁ।',
      'mod_titration_desc': 'ପ୍ରଶମନ ପ୍ରତିକ୍ରିୟା, ସୂଚକ ଏବଂ ସଠିକ୍ ପରୀକ୍ଷାଗାର ମାପ ଶିଖନ୍ତୁ।',

      // Badges, Shop & Collections
      'badge_explorer': 'ଅନୁସନ୍ଧାନକାରୀ',
      'badge_scientist': 'ବୈଜ୍ଞାନିକ',
      'badge_master': 'ମାଷ୍ଟର',
      'badge_champion': 'ଚାମ୍ପିଅନ୍',
      'shop_buy': 'କିଣନ୍ତୁ',
      'shop_owned': 'ନିଜର',
      'insufficient_coins_title': 'ଅଧିକ ମୁଦ୍ରା ଆବଶ୍ୟକ',
      'purchase_successful_title': 'କ୍ରୟ ସଫଳ ହେଲା!',
      'already_owned_title': 'ପୂର୍ବରୁ ଅଛି',
      'rank_student_header': 'ସ୍ଥାନ / ଛାତ୍ର',
      'total_score_header': 'ମୋଟ ସ୍କୋର',
    }
  };

  // Bidirectional English-phrase to Translation mapping dictionary
  static final Map<String, String> _phraseToKey = {
    'Continue Learning': 'continue_learning',
    'YOUR QUEST': 'your_quest',
    'CONTINUE QUEST': 'continue_quest',
    'START QUEST': 'start_quest',
    'QUICK REVISION': 'quick_revision',
    'My Modules': 'my_modules',
    'VIEW ALL': 'view_all',
    'VIEW ALL MODULES': 'view_all_modules',
    'Leaderboard': 'leaderboard',
    'YOUR CLASS': 'your_class',
    'VIEW LEADERBOARD': 'view_leaderboard',
    'Collection': 'collection',
    'Shop': 'shop',
    'Settings': 'settings',
    'Profile': 'profile',
    'Badges': 'badges',
    'Collectibles': 'collectibles',
    'Account': 'account',
    'Log Out': 'logout',
    'LOG OUT': 'logout',
    'Language': 'language',
    'Sound Effects': 'sound',
    'Student ID': 'student_id',
    'Notifications': 'notifications',
    'Quest Coins': 'quest_coins',
    'Level': 'level',
    'Roadmap': 'roadmap',
    'EXPLORE MODULES': 'explore_modules',
    'START YOUR FIRST QUEST': 'start_first_quest',
    'QUEST COMPLETE!': 'quest_complete',
    'Change Language': 'change_language',
    'DAILY MISSIONS': 'daily_missions',
    'WEEKLY MISSIONS': 'weekly_missions',
    'DAILY': 'daily',
    'WEEKLY': 'weekly',
    'CLAIM REWARD!': 'claim_reward_btn',
    'CLAIMED': 'claimed_btn',
    'Complete 2 Lessons': 'complete_2_lessons',
    'Earn 100 XP': 'earn_100_xp',
    'Finish 1 Simulation Lab': 'finish_1_simulation_lab',
    'Master 1 Full Module': 'master_1_full_module',
    'Earn 500 Weekly XP': 'earn_500_weekly_xp',
    'DAILY LOGIN REWARD': 'daily_login_reward',
    'CLAIM REWARD': 'claim_reward',
    'MYSTERY CHEST': 'mystery_chest',
    'REWARD CLAIMED!': 'reward_claimed',
    'ASK DENDY': 'ask_dendy',
    'Ask Dendy': 'ask_dendy',
    'Dendy AI Companion': 'dendy_companion',
    'Ask me anything about science or math!': 'ask_me_anything',
    'Listening...': 'listening',
    'Type your question...': 'type_question',
    'Ready for your next quest?': 'ready_next_quest',
    'You are almost done with this lesson!': 'almost_done_lesson',
    'Excellent! You completed all the physical science lab quests!': 'all_science_quests_complete',
    "Start your first quest! Let's find something new to explore!": 'start_first_quest_desc',
    'We will investigate the exact reasons and measurements in the next experiment lab!': 'investigate_reasons_lab',
    'DISCOVERY COMPLETE!': 'discovery_complete',
    'You made your predictions and tested them.': 'predictions_tested',
    'Carefully check the parameters before selecting your answer!': 'carefully_check_parameters',
    'Keep trying! Think about the density formula.': 'keep_trying_density_formula',
    'LAB DESCRIPTION': 'lab_description',
    'TITRATION OBJECTIVES': 'titration_objectives',
    'LEVEL UP!': 'level_up',
    'CONTINUE ADVENTURE': 'continue_adventure',
    'Bonus XP': 'bonus_xp',
    'Fantastic job! You mastered this challenge and earned rewards.': 'fantastic_job_mastered',
    'CONTINUE TO NEXT LESSON': 'continue_next_lesson',
    'A hollow steel ship floats because the air trapped inside its massive hull lowers its total average density below 1.00 kg/L.': 'steel_ship_explanation',
    'Ice Expands & Defies Normal Solids': 'ice_expands_title',
    'Water expands when freezing, giving ice a density of 0.92 kg/L. That is why ice floats and supports Arctic life.': 'ice_expands_body',
    'Liquids Naturally Layer by Density': 'liquids_layer_title',
    'When immiscible fluids meet, lighter fluids (like oil at ~0.92 kg/L) float on top of denser fluids (like water at 1.00 kg/L).': 'liquids_layer_body',

    // Interactive Lessons (Discover Density & Buoyancy)
    'LEVEL 1 • DISCOVER DENSITY': 'level_1_title',
    'CURIOSITY': 'curiosity',
    'EXPERIMENT': 'experiment',
    'APPLY': 'apply',
    'CHALLENGE': 'challenge',
    'TEACH DENDY': 'teach_dendy',
    'TEACH-BACK': 'teach_dendy',
    'DISCOVERY LAB • STEP 1': 'discovery_lab_step_1',
    'DISCOVER DENSITY': 'discover_density',
    'Discover Density': 'discover_density',
    '"Why do some objects float while others sink?"': 'why_objects_float_sink',
    'Why do some objects float while others sink?': 'why_objects_float_sink',
    'Before testing, predict what will happen when different materials are placed in water. Observe the physical results and notice what happens.': 'predict_before_test',
    'START DISCOVERY': 'start_discovery',
    "Let's make a prediction before we test anything!": 'predict_before_test_dendy',
    'WOODEN BLOCK': 'wooden_block',
    'Solid oak wood': 'solid_oak_wood',
    'METAL CUBE': 'metal_cube',
    'Solid iron/steel': 'solid_iron_steel',
    'PLASTIC BALL': 'plastic_ball',
    'Hollow lightweight plastic': 'hollow_plastic',
    'RIVER STONE': 'river_stone',
    'Dense smooth pebble': 'dense_pebble',
    'APPLE': 'apple',
    'Fresh crisp fruit': 'fresh_fruit',
    'FLOAT': 'float',
    'SINK': 'sink',
    'TEST HYPOTHESIS': 'test_hypothesis',
    'WATER TANK LAB': 'water_tank_lab',
    'TAP AN OBJECT TO TEST': 'tap_to_test',
    'WHAT DID YOU OBSERVE?': 'what_did_you_observe',
    'Wood & plastic float because they are less dense than water. Metal & stone sink because they are denser.': 'reflection_wood_plastic_float',
    'Heavy things always sink and light things always float.': 'reflection_heavy_sink',
    'Shape is the only reason objects float.': 'reflection_shape_only',
    'CONTINUE TO LESSON 2': 'continue_to_lesson_2',
    'LESSON 2: MEASURE DENSITY': 'lesson_2_measure_density',
    'MASS & VOLUME LAB': 'mass_volume_lab',
    'Change mass and volume to see density change in real time!': 'change_mass_volume_desc',
    'Mass (kg)': 'mass_kg',
    'Volume (L)': 'volume_l',
    'Density = Mass ÷ Volume': 'density_formula_desc',
    'Water Density: 1.00 kg/L': 'water_density_standard',
    'RESET LAB': 'reset_lab',
    'CONTINUE TO LESSON 3': 'continue_to_lesson_3',
    'LESSON 3: REAL-WORLD DENSITY': 'lesson_3_real_world',
    'APPLY YOUR KNOWLEDGE': 'apply_your_knowledge',
    'Why do huge steel ships float on water?': 'why_steel_ships_float_q',
    'Why does ice float on water?': 'why_ice_floats_q',
    'Why does oil float on water?': 'why_oil_floats_q',
    'LESSON 4: DENSITY DETECTIVE': 'lesson_4_detective',
    'MYSTERY OBJECTS': 'mystery_objects',
    'Identify which object is made of gold based on density!': 'identify_gold_desc',
    'SUBMIT ANSWER': 'submit_answer',
    'LESSON 5: TEACH DENDY': 'lesson_5_teach_dendy',
    'Explain to Dendy why objects float or sink using mass and volume!': 'explain_density_dendy',
    'DENSITY MASTERED': 'density_mastered',
    'LEVEL 1 COMPLETE': 'level_1_complete',
    'CLAIM REWARDS & UNLOCK LEVEL 2': 'claim_rewards_unlock_2',
    'SWITCH TO VOICE': 'SWITCH TO VOICE',
    'TYPE INSTEAD': 'TYPE INSTEAD',
    'SUBMIT EXPLANATION': 'SUBMIT EXPLANATION',
    'TAP TO SPEAK YOUR ANSWER': 'TAP TO SPEAK YOUR ANSWER',
    'LISTENING... TAP TO FINISH': 'LISTENING... TAP TO FINISH',
    'YOU SAID:': 'YOU SAID:',
    "Nice prediction. Now let's become scientists.": 'nice_prediction_become_scientists',
    "Let's experiment.": 'lets_experiment',
    "Try making this object heavier.": 'try_making_object_heavier',
    "What changed?": 'what_changed',
    "Sank deeper": 'sank_deeper',
    "Floated higher": 'floated_higher',
    "Nothing changed": 'nothing_changed',
    "What happens if we change the size instead?": 'what_happens_change_size',
    "What do you notice?": 'what_do_you_notice',
    "Now let's compare two objects side by side in the tank.": 'compare_two_objects',
    "Which one sinks more?": 'which_one_sinks_more',
    "The denser object": 'denser_heavier_object',
    "The lighter object": 'larger_lighter_object',
    "Both sink equally": 'both_sink_equally',
    "Compare Mode": 'compare_mode',
    "Single Object": 'single_mode',
    "Object A": 'object_a',
    "Object B": 'object_b',
    "Wood": 'mat_wood',
    "Ice": 'mat_ice',
    "Plastic": 'mat_plastic',
    "Steel": 'mat_steel',
    "Gold": 'mat_gold',
    "You've changed the mass.": 'youve_changed_mass',
    "You've changed the volume.": 'youve_changed_volume',
    "Can you spot the pattern?": 'can_you_spot_pattern',
    "THE DENSITY FORMULA": 'the_density_formula',
    "Density = Mass ÷ Volume": 'density_equals_mass_divided_volume',
    "When mass increases in the same volume, density goes up. When volume increases for the same mass, density goes down!": 'density_discovery_desc',
    "Less dense than water (< 1.00 kg/L) = FLOATS!": 'less_dense_than_water_floats',
    "Denser than water (> 1.00 kg/L) = SINKS!": 'more_dense_than_water_sinks',

    // Greeting & Stats
    'Hi': 'greeting_hi',
    'TOTAL XP': 'total_xp',
    'COINS': 'coins',
    'COMPLETED': 'stat_completed',
    'BADGES': 'stat_badges',
    'COLLECTIBLES': 'stat_collectibles',
    'OFFLINE SYNC': 'stat_offline_sync',
    'Ready': 'ready',
    'Earned': 'earned',
    'Unlocked': 'unlocked',
    'Modules': 'modules',
    'Lessons': 'lessons',
    'Levels': 'levels',
    'OBJECTIVES:': 'objectives_header',

    // Subjects & Modules
    'SCIENCE': 'SCIENCE',
    'MATHEMATICS': 'MATHEMATICS',
    'CHEMISTRY': 'CHEMISTRY',
    'PHYSICS': 'PHYSICS',
    'VIRTUAL LAB': 'VIRTUAL LAB',
    'Density & Buoyancy': 'mod_density_title',
    'Fractions': 'mod_fractions_title',
    'Acid-Base Titration': 'mod_titration_title',
    'Ratio & Proportions': 'mod_ratios_title',
    'Explore the physics of mass, volume, and how materials behave in fluids.': 'mod_density_desc',
    'Master parts of a whole, visual fractions, and equivalent ratios.': 'mod_fractions_desc',
    'Master neutralization reactions, indicators, and precise lab measurements.': 'mod_titration_desc',

    // Badges & Shop
    'Explorer': 'badge_explorer',
    'Scientist': 'badge_scientist',
    'Master': 'badge_master',
    'Champion': 'badge_champion',
    'EARNED': 'earned',
    'LOCKED': 'locked',
    'BUY': 'shop_buy',
    'OWNED': 'shop_owned',
    'INSUFFICIENT COINS': 'insufficient_coins_title',
    'PURCHASE SUCCESSFUL!': 'purchase_successful_title',
    'ALREADY OWNED': 'already_owned_title',
    'RANK / STUDENT': 'rank_student_header',
    'TOTAL SCORE': 'total_score_header',
  };

  static void init(StorageService storage) {
    _currentLanguage = storage.getLanguage();
    languageNotifier.value = _currentLanguage;
  }

  static Future<void> setLanguage(StorageService storage, String langCode) async {
    if (_localizedValues.containsKey(langCode)) {
      _currentLanguage = langCode;
      languageNotifier.value = langCode;
      await storage.saveLanguage(langCode);

      final currentStudent = Locator.studentRepository.getCurrentStudent();
      if (currentStudent != null) {
        final updated = currentStudent.copyWith(language: langCode);
        await Locator.studentRepository.updateStudentProfile(updated);
      }
    }
  }

  static String translate(String keyOrText, {String? targetLanguage, Map<String, String>? args}) {
    final lang = targetLanguage ?? _currentLanguage;
    final dict = _localizedValues[lang] ?? _localizedValues['en']!;

    // 1. Direct key match
    if (dict.containsKey(keyOrText)) {
      String val = dict[keyOrText]!;
      if (args != null) {
        args.forEach((k, v) => val = val.replaceAll('{$k}', v));
      }
      return val;
    }

    // 2. Direct English phrase match from dictionary
    final mappedKey = _phraseToKey[keyOrText.trim()];
    if (mappedKey != null && dict.containsKey(mappedKey)) {
      String val = dict[mappedKey]!;
      if (args != null) {
        args.forEach((k, v) => val = val.replaceAll('{$k}', v));
      }
      return val;
    }

    // 3. Fallback to English dictionary lookup
    final enDict = _localizedValues['en']!;
    if (enDict.containsKey(keyOrText)) {
      String val = enDict[keyOrText]!;
      if (args != null) {
        args.forEach((k, v) => val = val.replaceAll('{$k}', v));
      }
      return val;
    }

    // Return original string if untranslated
    String result = keyOrText;
    if (args != null) {
      args.forEach((k, v) => result = result.replaceAll('{$k}', v));
    }
    return result;
  }
}

// Global short translation helper function
String l(String key, {Map<String, String>? args}) {
  return LocalizationService.translate(key, args: args);
}
